apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8080
  type: {{ .Values.service.type }}
