name: Static Go CI/CD

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'docs/**'
            - 'README.md'
            - 'helm/**'

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./static-go

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            
            - name: List files
              run: ls -la

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'

            - name: Cache Go modules
              uses: actions/cache@v3
              with: 
                path: |
                      ~/.cache/go-build
                      ~/go/pkg/mod
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                      ${{ runner.os }}-go-

            - name: Install dependencies
              run: go mod download

            - name: Run tests
              run: go test ./... -v

            - name: Build the application
              run: go build -o my-app .

    code-quality:
        runs-on: ubuntu-latest
        needs: build
        defaults:
          run:
            working-directory: ./static-go


        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.21'


            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v6
              with:
                version: v1.64.7
                args: ./static-go/...